env:
  dev:
    input:
      split:
        database: "dev"
        table: "split"
      forecast_on_test:
        database: "dev"
        table: "forecast_on_test"
      all_models_forecast:
        database: "dev"
        table: "all_models_forecast"
    output:
      metrics:
        database: "dev"
        table: "metrics"
      best_models:
        database: "dev"
        table: "best_models"
      forecast:
        database: "dev"
        table: "forecast"
    group_columns: ["store", "item"]
    time_column: "date"
    target_column: "sales"
    metrics: ["rmse", "mae", "mape"]
    model_selection_metric: "mape"
    execution_date: "2018-01-01"
    freq: "1D"
  staging:
    input:
      split:
        database: "staging"
        table: "split"
      forecast_on_test:
        database: "staging"
        table: "forecast_on_test"
      all_models_forecast:
        database: "staging"
        table: "all_models_forecast"
    output:
      metrics:
        database: "staging"
        table: "metrics"
      best_models:
        database: "staging"
        table: "best_models"
      forecast:
        database: "staging"
        table: "forecast"
    group_columns: ["store", "item"]
    time_column: "date"
    target_column: "sales"
    metrics: ["rmse", "mae", "mape"]
    model_selection_metric: "mape"
    execution_date: "2018-01-01"
    freq: "1D"
  prod:
    input:
      split:
        database: "prod"
        table: "split"
      forecast_on_test:
        database: "prod"
        table: "forecast_on_test"
      all_models_forecast:
        database: "prod"
        table: "all_models_forecast"
    output:
      metrics:
        database: "prod"
        table: "metrics"
      best_models:
        database: "prod"
        table: "best_models"
      forecast:
        database: "prod"
        table: "forecast"
    group_columns: ["store", "item"]
    time_column: "date"
    target_column: "sales"
    metrics: ["rmse", "mae", "mape"]
    model_selection_metric: "mape"
    execution_date: "2018-01-01"
    freq: "1D"
