env:
  dev:
    input:
      database: "dev"
      table: "split"
    output:
      forecast_on_test:
        database: "dev"
        table: "forecast_on_test"
      all_models_forecast:
        database: "dev"
        table: "all_models_forecast"
    group_columns: ["store", "item"]
    time_column: "date"
    target_column: "sales"
    model_params:
      seasonal_periods: 7
    test_size: 90
    steps: 7
    execution_date: "2018-01-01"
    freq: "1D"
  staging:
    input:
      database: "staging"
      table: "split"
    output:
      forecast_on_test:
        database: "staging"
        table: "forecast_on_test"
      all_models_forecast:
        database: "staging"
        table: "all_models_forecast"
    group_columns: ["store", "item"]
    time_column: "date"
    target_column: "sales"
    model_params:
      seasonal_periods: 7
    test_size: 90
    steps: 7
    execution_date: "2018-01-01"
    freq: "1D"
  prod:
    input:
      database: "prod"
      table: "split"
    output:
      forecast_on_test:
        database: "prod"
        table: "forecast_on_test"
      all_models_forecast:
        database: "prod"
        table: "all_models_forecast"
    group_columns: ["store", "item"]
    time_column: "date"
    target_column: "sales"
    model_params:
      seasonal_periods: 7
    test_size: 90
    steps: 7
    execution_date: "2018-01-01"
    freq: "1D"
