env:
  dev:
    experiment: "/Shared/dbx/dbx_demand_forecast/dev_dbx_demand_forecast"
    input:
      path: "abfss://dbx-demand-forecast@databricksucatalog.dfs.core.windows.net/dev/sales"
      sep: ","
    output:
      database: "dev"
      table: "input"
  staging:
    experiment: "/Shared/dbx/dbx_demand_forecast/staging_dbx_demand_forecast"
    input:
      path: "abfss://dbx-demand-forecast@databricksucatalog.dfs.core.windows.net/staging/sales"
      sep: ","
    output:
      database: "staging"
      table: "input"
  prod:
    experiment: "/Shared/dbx/dbx_demand_forecast/prod_dbx_demand_forecast"
    input:
      path: "abfss://dbx-demand-forecast@databricksucatalog.dfs.core.windows.net/prod/sales"
      sep: ","
    output:
      database: "prod"
      table: "input"
