common: &common
  env: dev
  tz: America/Santiago
  execution_date: 2018-01-01
  database: dev
time_serie: &time_serie
  group_columns: [store, item]
  time_column: date
  target_column: sales
create_database:
  <<:
    - *common
ingestion:
  <<:
    - *common
  path: "data/train.csv"
  sep: ","
  stores: [1]
split:
  <<:
    - *common
    - *time_serie
  time_delta: 728
  test_size: 21
  freq: 1D
model: &model
  <<:
    - *common
    - *time_serie
  test_size: 21
  steps: 21
  freq: 1D
models:
  ExponentialSmoothing:
    <<: *model
    model_cls: ExponentialSmoothing
    model_params:
      seasonal_periods: 7
  AutoARIMA:
    <<: *model
    model_cls: AutoARIMA
    model_params:
      maxiter: 10
  Prophet:
    <<: *model
    model_cls: Prophet
    model_params:
      country_holidays: CL
  XGBModel:
    <<: *model
    model_cls: XGBModel
    model_params:
      objective: reg:squarederror
      lags: 7
      nthread: 1
      max_depth: 6
      learning_rate: 0.3
      gamma: 0
      lambda: 1
      alpha: 0
  RandomForest:
    <<: *model
    model_cls: RandomForest
    model_params:
      lags: 7
      n_jobs: 1
      n_estimators: 100
      max_depth: 6
  Croston:
    <<: *model
    model_cls: Croston
    model_params:
      version: sba
  NaiveMean:
    <<: *model
    model_cls: NaiveMean
  NaiveMovingAverage:
    <<: *model
    model_cls: NaiveMovingAverage
    model_params:
      input_chunk_length: 7
evaluation:
  <<:
    - *common
    - *time_serie
  metrics: [rmse, mae, mape]
  model_selection_metric: mape
  freq: 1D
